# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    connection-timeout: 5000ms
  port: 8080
  servlet:
    context-path: /fg_basic_system

spring:
  # 环境配置 dev|prod
  profiles:
    active: prod
  # jackson时间格式化
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
#  mvc:
#    view:
#      prefix: /templates/
#      suffix: .html
  thymeleaf:
    prefix:
      classpath: /templates   # 访问template下的html文件需要配置模板，映射
    cache: false # 开发时关闭缓存,不然没法看到实时页面
#mybatis-plus
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: fg.system.modules.admin.*.entity;fg.system.modules.*.entity
  global-config:
    #数据库相关配置
    db-config:
      id-type: AUTO
      logic-delete-value: -1
      logic-not-delete-value: 0
    banner: false
 #原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'

knife4j:
  setting:
  #关闭文档中的SwaggerModels菜单
    enableSwaggerModels: false